FROM gradle:8.7-jdk17

WORKDIR /app

# gradle 캐시 최적화
COPY build.gradle settings.gradle ./
COPY gradle ./gradle
RUN gradle build -x test || true

# 실제 소스는 volume mount로 연결될 예정
EXPOSE 8080

CMD ["gradle", "bootRun"]
