package techtrek.global.config;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import techtrek.domain.enterprise.entity.Enterprise;
import techtrek.domain.enterprise.repository.EnterpriseRepository;
import techtrek.domain.interviewQuestion.entity.InterviewQuestion;
import techtrek.domain.interviewQuestion.repository.InterviewQuestionRepository;

import java.util.List;

@Configuration
@RequiredArgsConstructor
public class DataInitializer {

    // 기업, 기업 질문 생성
    @Bean
    ApplicationRunner initializeDatabase(EnterpriseRepository enterpriseRepository,
                                         InterviewQuestionRepository questionRepository) {
        return args -> {
            List<String> enterpriseNames = List.of(
                    "SAMSUNG", "COUPANG", "NAVER", "KAKAO",
                    "BAEMIN", "DANGGEUN_MARKET", "TOSS", "NEXON"
            );

            for (String name : enterpriseNames) {
                enterpriseRepository.findByName(name)
                        .orElseGet(() -> enterpriseRepository.save(
                                Enterprise.builder().name(name).build()
                        ));
            }

            Enterprise samsung = enterpriseRepository.findByName("SAMSUNG").orElseThrow();
            Enterprise naver = enterpriseRepository.findByName("NAVER").orElseThrow();
            Enterprise coupang = enterpriseRepository.findByName("COUPANG").orElseThrow();
            Enterprise kakao = enterpriseRepository.findByName("KAKAO").orElseThrow();
            Enterprise baemin = enterpriseRepository.findByName("BAEMIN").orElseThrow();
            Enterprise danggeun = enterpriseRepository.findByName("DANGGEUN_MARKET").orElseThrow();
            Enterprise toss = enterpriseRepository.findByName("TOSS").orElseThrow();
            Enterprise nexon = enterpriseRepository.findByName("NEXON").orElseThrow();

            List<InterviewQuestion> questions = List.of(
                    // 삼성
                    new InterviewQuestion("멀티 스레드와 멀티 프로세스 차이는 무엇인가요?", "스레드는 같은 메모리 공간, 경량 / 프로세스: 독립된 메모리 공간, 무거움", samsung, "OS"),
                    new InterviewQuestion("Thread와 Process의 차이는 무엇인가요?", "Thread: 실행 단위 / Process: 자원 단위, 독립 실행", samsung, "OS"),
                    new InterviewQuestion("동기와 비동기란 무엇인가요?", "동기: 순차 실행 / 비동기: 비순차 실행, 기다리지 않고 처리", samsung, "OS"),
                    new InterviewQuestion("세마포어 개념을 설명해 주세요.", "공유 자원 접근 제어, 신호 기반 동기화", samsung, "OS"),
                    new InterviewQuestion("크리티컬 섹션이란 무엇인가요?", "한 번에 하나의 스레드만 접근 가능한 코드 영역", samsung, "OS"),
                    new InterviewQuestion("데드락(Deadlock) 설명해 주세요.", "서로 자원을 점유하며 무한 대기 상태", samsung, "OS"),
                    new InterviewQuestion("OS에 대해 설명해 주세요.", "하드웨어와 소프트웨어 간 인터페이스 제공, 자원 관리", samsung, "OS"),
                    new InterviewQuestion("힙과 스택 설명해 주세요.", "스택: LIFO, 지역 변수 / 힙: 동적 메모리 할당", samsung, "OS"),
                    new InterviewQuestion("배열(Array)과 리스트(List)의 차이와 검색에 더 용이한 것은 어떤거고 이유는 무엇인가요?", "배열은 고정 크기 연속 메모리로 인덱스 접근이 빨라 검색에 유리, 리스트는 동적 크기와 삽입/삭제 유리.", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("배열(Array)과 연결 리스트(Linked List)의 차이점과 장단점은 무엇인가요?", "배열: 연속 메모리, 빠른 인덱스 접근 / 연결 리스트: 포인터 기반, 삽입/삭제 유리", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("Array, List, 배열의 차이점은 무엇인가요?", "Array: 고정 크기 / List: 동적 / 배열: 일반 용어", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("해시 테이블(Hash Table)이란 무엇인가요?", "키-값 쌍 저장, 빠른 검색", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("해시 테이블 충돌을 해결하는 방법은 무엇인가요?", "체이닝이나 개방 주소법으로 해결.", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("이진트리와 이진 탐색 트리 차이점은 무엇인가요?", "이진트리: 일반 트리 / 이진 탐색 트리: 정렬 유지", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("그래프와 인접 리스트/인접 행렬 표현 방법의 차이는 무엇인가요?", "리스트: 메모리 효율적 / 행렬: 빠른 연결 확인", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("스택(Stack)과 큐(Queue)의 동작 방식은 무엇인가요?", "스택: LIFO / 큐: FIFO", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("힙과 스택에 대해 설명해주세요.", "힙: 동적 메모리 / 스택: 함수 호출, 지역 변수 저장", samsung, "DATA_STRUCTURE"),
                    new InterviewQuestion("퀵소트(Quick Sort) 알고리즘이 무엇인가요?", "피벗 기준으로 분할해 재귀적으로 정렬하는 효율적 정렬 알고리즘.", samsung, "ALGORITHM"),
                    new InterviewQuestion("버블 정렬, 선택 정렬, 삽입 정렬의 차이점은 무엇인가요?", "버블: 인접 비교 / 선택: 최소값 선택 / 삽입: 정렬된 위치 삽입", samsung, "ALGORITHM"),
                    new InterviewQuestion("DFS와 BFS의 차이는 무엇인가요?", "DFS: 깊이 우선 / BFS: 너비 우선", samsung, "ALGORITHM"),
                    new InterviewQuestion("BFS 알고리즘에 대해 설명해주세요.", "그래프/트리 너비 우선 탐색", samsung, "ALGORITHM"),
                    new InterviewQuestion("DFS 알고리즘에 대해 설명해주세요.", "그래프/트리 깊이 우선 탐색", samsung, "ALGORITHM"),
                    new InterviewQuestion("이진 탐색(Binary Search) 동작 원리는 무엇인가요?", "정렬된 배열에서 중간값과 비교 후 탐색 범위 반으로 축소", samsung, "ALGORITHM"),
                    new InterviewQuestion("재귀(Recursion)와 반복(Iteration)의 차이는 무엇인가요?", "재귀: 자기 자신 호출 / 반복: 루프 사용", samsung, "ALGORITHM"),
                    new InterviewQuestion("다이나믹 프로그래밍(Dynamic Programming) 개념은 무엇인가요?", "문제를 작은 문제로 나누고 결과 재사용", samsung, "ALGORITHM"),
                    new InterviewQuestion("탐색 알고리즘에는 어떤 것들이 있나요?", "선형, 이진, 해시 탐색 등", samsung, "ALGORITHM"),
                    new InterviewQuestion("재귀함수가 무엇인가요? 재귀함수 장단점은?", "자기 자신을 호출 / 장점: 코드 간결, 단점: 스택 오버플로우 가능", samsung, "ALGORITHM"),
                    new InterviewQuestion("XML 파싱하는 알고리즘을 간략히 설명해 주세요.", "DOM: 문서 전체 로드, SAX: 이벤트 기반 순차 처리", samsung, "ALGORITHM"),
                    new InterviewQuestion("탐색 알고리즘에 대해 설명해 주세요.", "선형, 이진, 그래프 탐색 등 데이터 탐색 방법", samsung, "ALGORITHM"),
                    new InterviewQuestion("버블 정렬, 선택 정렬, 삽입 정렬의 차이점은 무엇인가요?", "버블: 인접 교환 / 선택: 최소값 선택 / 삽입: 정렬 위치 삽입", samsung, "ALGORITHM"),
                    new InterviewQuestion("DFS와 BFS 차이점을 설명해주세요.", "DFS는 깊이 우선, BFS는 너비 우선으로 탐색하며 BFS는 최단 경로에 유리.", samsung, "ALGORITHM"),
                    new InterviewQuestion("해시 알고리즘에 대해 설명해주세요.", "데이터를 고정 크기 값으로 변환해 검색, 인증, 무결성에 활용.", samsung, "ALGORITHM"),
                    new InterviewQuestion("선형 알고리즘에 대해 설명해주세요.", "연산이 입력 크기에 비례하는 알고리즘", samsung, "ALGORITHM"),
                    new InterviewQuestion("OSI 7 Layer 설명해 주세요.", "물리-데이터링크-네트워크-전송-세션-표현-응용 계층으로 구성.", samsung, "NETWORK"),
                    new InterviewQuestion("TCP/IP 설명해 주세요.", "전송 계층(TCP/UDP) + 인터넷 계층(IP) 기반 통신 프로토콜", samsung, "NETWORK"),
                    new InterviewQuestion("TCP/UDP 차이 설명해 주세요.", "TCP: 연결 지향, 신뢰성 보장 / UDP: 비연결, 속도 우선", samsung, "NETWORK"),
                    new InterviewQuestion("IoT 실시간 통신에 사용할 수 있는 프로토콜 두 가지와 특징은 무엇인가요?", "MQTT: 경량, 저전력 / CoAP: REST 기반, 제약 환경 적합", samsung, "NETWORK"),
                    new InterviewQuestion("프로토콜에 대해 설명헤주세요.", "통신 규칙과 데이터 교환 방식 정의.", samsung, "NETWORK"),
                    new InterviewQuestion("웹소켓 통신과 HTTP 요청/응답 방식의 차이는 무엇인가요?", "웹소켓: 양방향 실시간 / HTTP: 요청-응답 단방향", samsung, "NETWORK"),
                    new InterviewQuestion("DB의 통신 방법은 무엇인가요?", "SQL 쿼리, JDBC/ODBC 등 클라이언트-서버 통신", samsung, "DATABASE"),
                    new InterviewQuestion("Connection Pool이란 무엇인가요?", "DB 연결 재사용으로 성능 향상", samsung, "DATABASE"),
                    new InterviewQuestion("DBA 스키마 사상 논하세요.", "논리-물리 구조 매핑 과정", samsung, "DATABASE"),
                    new InterviewQuestion("RDBS에 대해서 이야기해 주세요.", "관계형 DB 관리 시스템, 테이블 기반 저장", samsung, "DATABASE"),
                    new InterviewQuestion("SQL과 NoSQL의 다른 점은 무엇인가요?", "SQL: 정형 데이터, 스키마 필요 / NoSQL: 비정형, 유연", samsung, "DATABASE"),
                    new InterviewQuestion("Hash 함수에 대해 설명해주세요.", "입력 데이터를 고정 길이 값으로 매핑, 검색/보안 활용", samsung, "DATABASE"),
                    new InterviewQuestion("디자인패턴에 대해 설명해 주세요.", "반복되는 문제 해결을 위해 설계된 재사용 가능한 템플릿", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("Singleton이란 무엇인가요?", "인스턴스를 하나만 생성하고 전역에서 접근 가능하도록 하는 패턴", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("Singleton Pattern 설명해 주세요.", "클래스 인스턴스를 단 하나만 생성, 전역 접근 제공", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("Object Oriented Programming은 무엇인가요?", "객체와 클래스 기반 프로그래밍 패러다임", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향과 절차지향 언어의 차이점은 무엇인가요?", "객체지향: 데이터+메서드 / 절차지향: 순차적 코드", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("추상클래스와 인터페이스의 차이점은 무엇인가요?", "추상클래스: 일부 구현 가능 / 인터페이스: 구현 불가, 다중 상속 가능", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("Override와 Overload의 차이는 무엇인가요?", "Override: 상속 메서드 재정의 / Overload: 같은 이름 다른 매개변수", samsung, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("다형성에 대해 설명해 주세요.", "동일 인터페이스로 다양한 객체를 다루는 능력", samsung, "SOFTWARE_DESIGN"),

                    // 네이버
                    new InterviewQuestion("프로세스(Process)와 스레드(Thread)의 차이는 무엇인가요?","프로세스는 독립된 실행 단위이고, 스레드는 프로세스 내에서 실행되는 작은 단위입니다.", naver,"OS"),
                    new InterviewQuestion("C 언어에서 프로세스 공간(Process Memory Space)은 어떻게 구성되나요?","코드, 데이터, 힙(Heap), 스택(Stack) 영역으로 나눠집니다.", naver,"OS"),
                    new InterviewQuestion("64비트와 32비트의 차이는 무엇인가요?","한 번에 처리할 수 있는 데이터 크기와 주소 공간의 크기가 다릅니다.", naver,"OS"),
                    new InterviewQuestion("동시성 문제(Concurrency Issue)는 왜 발생하나요?","여러 스레드가 같은 자원을 동시에 접근할 때 발생합니다.", naver,"OS"),
                    new InterviewQuestion("리소스(Resource) 경합 문제 발생 시 해결 방안은 무엇인가요?","락(Lock), 세마포어(Semaphore) 같은 동기화 기법을 사용합니다.", naver,"OS"),
                    new InterviewQuestion("서버에서 타임아웃 에러(Timeout Error)가 발생했을 때 가장 먼저 확인해야 할 것은 무엇인가요?","네트워크 연결 상태와 서버 응답 지연 원인을 확인합니다.", naver,"OS"),
                    new InterviewQuestion("생명주기(Lifecycle)란 무엇인가요?","객체나 프로세스가 생성, 실행, 종료되는 과정을 말합니다.", naver,"OS"),
                    new InterviewQuestion("스택(Stack)과 힙(Heap) 메모리의 차이는 무엇인가요?","스택은 정적 메모리, 힙은 동적 메모리 할당에 사용됩니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("오버플로우(Overflow)란 무엇인가요?","할당된 메모리 범위를 초과해 데이터가 저장되는 현상입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("원형 스택(Circular Stack)의 공간 처리 문제는 무엇인가요?","포인터가 순환하면서 빈 공간을 제대로 활용하지 못할 수 있습니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("스택(Stack)과 링크드 리스트(Linked List)의 차이는 무엇인가요?","스택은 선형 구조이고, 링크드 리스트는 포인터로 연결된 동적 구조입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("연결 리스트(Linked List)로 구현된 스택(Stack)과 큐(Queue)의 차이는 무엇인가요?","스택은 LIFO, 큐는 FIFO 방식으로 동작합니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("이진 트리(Binary Tree)란 무엇인가요?","각 노드가 최대 두 개의 자식을 가지는 트리 구조입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("인덱스(Index)는 어떤 자료구조로 이루어져 있나요?","주로 B-트리(B-Tree) 또는 해시(Hash) 구조로 이루어집니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("리스트(List), 스택(Stack), 큐(Queue)의 차이는 무엇인가요?","리스트는 순차 자료구조, 스택은 LIFO, 큐는 FIFO입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("벡터(Vector)와 리스트(List)의 차이는 무엇인가요?","벡터는 배열 기반, 리스트는 노드 기반 구조입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("링크드 리스트(Linked List), 맵(Map), 해시맵(HashMap)의 특징은 무엇인가요?","링크드 리스트는 순차 연결, 맵은 키-값 저장, 해시맵은 빠른 탐색을 지원합니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("STL 리스트(List)와 벡터(Vector)의 차이와 장단점은 무엇인가요?","리스트는 삽입/삭제가 빠르고, 벡터는 접근 속도가 빠릅니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("해시 테이블(Hash Table)이란 무엇인가요?","키를 해시 함수로 변환해 값을 저장하는 자료구조입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("벡터(Vector)와 배열(Array)의 차이는 무엇인가요?","배열은 고정 크기, 벡터는 동적 크기를 가집니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("링크드 리스트(LinkedList)와 배열 리스트(ArrayList)의 차이는 무엇인가요?","링크드 리스트는 삽입/삭제가 빠르고, 배열 리스트는 인덱스 접근이 빠릅니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("집합(Set)과 리스트(List)의 차이는 무엇인가요?","집합은 중복 불허, 리스트는 중복 허용입니다.", naver,"DATA_STRUCTURE"),
                    new InterviewQuestion("버블 정렬(Bubble Sort)이란 무엇인가요?","인접한 두 원소를 비교해 교환하며 정렬하는 방식입니다.", naver,"ALGORITHM"),
                    new InterviewQuestion("정렬(Sorting) 알고리즘의 종류와 동작 방식은 무엇인가요?","버블, 선택, 삽입, 퀵, 병합 정렬 등이 있으며 비교와 교환 방식이 다릅니다.", naver,"ALGORITHM"),
                    new InterviewQuestion("최소 비용 신장 트리(MST, Minimum Spanning Tree)를 구하는 방법은 무엇인가요?","크루스칼(Kruskal)과 프림(Prim) 알고리즘을 사용합니다.", naver,"ALGORITHM"),
                    new InterviewQuestion("동적 계획법(Dynamic Programming, DP)이란 무엇인가요?","큰 문제를 작은 문제로 나누어 저장하며 해결하는 방법입니다.", naver,"ALGORITHM"),
                    new InterviewQuestion("전체 데이터에서 중앙값(Median)을 구하는 방법은 무엇인가요?","정렬 후 중간 값을 찾거나 힙(Heap)으로 효율적으로 구할 수 있습니다.", naver,"ALGORITHM"),
                    new InterviewQuestion("HTTP 통신 과정은 어떻게 이루어지나요?","클라이언트가 요청을 보내고 서버가 응답을 반환합니다.", naver,"NETWORK"),
                    new InterviewQuestion("쿠키(Cookie)란 무엇인가요?","클라이언트에 저장되는 작은 데이터 조각으로 상태 유지를 돕습니다.", naver,"NETWORK"),
                    new InterviewQuestion("HTTP 헤더(Header)란 무엇인가요?","요청 및 응답에 포함되는 메타데이터입니다.", naver,"NETWORK"),
                    new InterviewQuestion("OSI 7계층(OSI 7-Layer)이란 무엇인가요?","네트워크 통신을 7단계로 나눈 모델입니다.", naver,"NETWORK"),
                    new InterviewQuestion("HTTP 메서드(Method)의 종류와 특징은 무엇인가요?","GET, POST, PUT, DELETE 등 요청의 성격을 정의합니다.", naver,"NETWORK"),
                    new InterviewQuestion("브라우저에 naver.com을 입력했을 때 어떤 일이 일어나나요?","DNS 조회, TCP 연결, HTTP 요청, 서버 응답 후 렌더링이 진행됩니다.", naver,"NETWORK"),
                    new InterviewQuestion("TCP와 UDP의 장단점은 무엇인가요?","TCP는 신뢰성이 높고, UDP는 속도가 빠릅니다.", naver,"NETWORK"),
                    new InterviewQuestion("HTTP와 HTTPS의 차이는 무엇인가요?","HTTPS는 SSL/TLS로 암호화된 안전한 통신을 제공합니다.", naver,"NETWORK"),
                    new InterviewQuestion("TCP 3웨이 핸드셰이크(3-Way Handshake)는 무엇인가요?","연결 수립을 위해 SYN, SYN-ACK, ACK를 교환합니다.", naver,"NETWORK"),
                    new InterviewQuestion("RTP와 RTCP의 차이는 무엇인가요?","RTP는 미디어 전송, RTCP는 품질 제어 및 피드백을 담당합니다.", naver,"NETWORK"),
                    new InterviewQuestion("RESTful API란 무엇인가요?","자원을 URI로 표현하고 HTTP 메서드로 조작하는 아키텍처 스타일입니다.", naver,"NETWORK"),
                    new InterviewQuestion("CORS(Cross-Origin Resource Sharing)란 무엇인가요?","다른 출처 간 자원 공유를 허용하기 위한 정책입니다.", naver,"NETWORK"),
                    new InterviewQuestion("쿼리(Query)를 효과적으로 저장하는 방법은 무엇인가요?","해시 테이블(Hash Table)이나 인덱스를 사용합니다.", naver,"DATABASE"),
                    new InterviewQuestion("데이터베이스에 10억 개의 데이터가 있을 때 처리 방법은 무엇인가요?","인덱스, 파티셔닝, 분산 DB를 활용합니다.", naver,"DATABASE"),
                    new InterviewQuestion("트랜잭션(Transaction)이란 무엇인가요?","데이터베이스 작업의 최소 단위로, 원자성을 보장합니다.", naver,"DATABASE"),
                    new InterviewQuestion("인메모리 데이터베이스(In-Memory DB)와 MySQL의 차이는 무엇인가요?","인메모리는 속도가 빠르지만 휘발성, MySQL은 영속성을 가집니다.", naver,"DATABASE"),
                    new InterviewQuestion("오버플로우(Overflow)는 왜 발생하나요?","표현할 수 있는 범위를 초과했을 때 발생합니다.", naver,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("프레임워크(Framework)와 라이브러리(Library)의 차이는 무엇인가요?","프레임워크는 제어의 역전(IoC), 라이브러리는 호출하여 사용합니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("단일 책임 원칙(SRP, Single Responsibility Principle)을 위반하면 어떤 문제가 생기나요?","유지보수성과 확장성이 떨어집니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("싱글톤 패턴(Singleton Pattern)이란 무엇인가요?","하나의 인스턴스만 생성되도록 보장하는 패턴입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향(Object-Oriented)과 다형성(Polymorphism)이란 무엇인가요?","객체지향은 캡슐화/상속/다형성을 기반으로 한 설계 방식입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향 프로그래밍(OOP)의 장단점은 무엇인가요?","재사용성과 유지보수가 뛰어나지만, 복잡성이 증가할 수 있습니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("상속(Inheritance)의 장단점은 무엇인가요?","코드 재사용성이 높지만, 결합도가 증가할 수 있습니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("디자인 패턴(Design Pattern)이란 무엇인가요?","소프트웨어 설계에서 반복되는 문제 해결 방안입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("스레드 동기화(Thread Synchronization)의 방법과 장단점은 무엇인가요?","뮤텍스(Mutex), 세마포어(Semaphore) 등이 있으며 성능 저하가 단점입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("더블 버퍼링(Double Buffering)의 문제점은 무엇인가요?","메모리 사용량 증가와 동기화 지연이 발생할 수 있습니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("라이브러리(Library)와 DLL의 차이와 장단점은 무엇인가요?","라이브러리는 정적 연결, DLL은 동적 연결 방식입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("자바(Java)의 접근 제한자(Access Modifier)는 무엇인가요?","public, private, protected, default가 있습니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("자바(Java)에서 static과 final 키워드의 차이는 무엇인가요?","static은 공용 메모리 사용, final은 수정 불가를 의미합니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Call by Value와 Call by Reference의 차이는 무엇인가요?","값 복사와 참조 전달의 차이입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("안드로이드(Android)의 브로드캐스트 리시버(Broadcast Receiver)란 무엇인가요?","시스템 이벤트를 수신하는 구성 요소입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("뷰(View)와 프래그먼트(Fragment)의 차이는 무엇인가요?","뷰는 UI 구성 요소, 프래그먼트는 화면 일부를 담당하는 모듈입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("쿠버네티스(Kubernetes)의 장단점은 무엇인가요?","확장성과 자동화에 강점이 있지만 복잡성이 큽니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("WSGI(Web Server Gateway Interface)란 무엇인가요?","파이썬 웹 서버와 애플리케이션을 연결하는 인터페이스입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("ISO27001의 통제 항목은 무엇인가요?","정보 보안 정책, 자산 관리, 접근 통제 등입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("AOP(Aspect Oriented Programming)란 무엇인가요?","핵심 로직과 횡단 관심사를 분리하는 프로그래밍 기법입니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MSA(Microservices Architecture)의 장단점은 무엇인가요?","확장성이 높지만 서비스 관리가 복잡해집니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("정렬(Sorting) 문제에서 효율적인 저장 방식은 무엇인가요?","바이너리 서치(Binary Search)와 해시 테이블(Hash Table)을 사용합니다.", naver,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향 프로그래밍(OOP)의 개념은 무엇인가요?","객체 단위로 코드와 데이터를 묶어 관리하는 프로그래밍 패러다임입니다.", naver,"SOFTWARE_DESIGN"),

                    // 쿠팡
                    new InterviewQuestion("프로세스(Process)와 스레드(Thread)의 차이를 설명해 주세요","프로세스는 독립된 실행 단위이고, 스레드는 같은 메모리를 공유하는 경량 실행 단위입니다. 스레드는 컨텍스트 전환 비용이 적습니다.", coupang, "OS"),
                    new InterviewQuestion("멀티태스킹이 무엇인지 설명해 주세요","멀티태스킹은 CPU를 여러 작업에 분할하여 동시에 실행하는 것처럼 처리하는 방식입니다.", coupang, "OS"),
                    new InterviewQuestion("캐시는 왜 사용하는지 설명해 주세요","캐시는 접근 속도가 빠른 메모리로, 자주 쓰는 데이터를 저장해 시스템 성능을 높입니다.", coupang, "OS"),
                    new InterviewQuestion("스택(Stack)의 특징과 사용 예시를 설명해 주세요","스택은 LIFO 구조로, 함수 호출, 뒤로 가기 기능 등에서 사용됩니다.", coupang, "DATA_STRUCTURE"),
                    new InterviewQuestion("컬렉션(Collection)에 대해 설명해 주세요","컬렉션은 객체를 저장하고 관리하는 자료구조의 집합으로, List, Set, Map 등이 있습니다.", coupang, "DATA_STRUCTURE"),
                    new InterviewQuestion("해시테이블(Hash Table)이 무엇인지 설명해 주세요","키와 값을 매핑하여 빠르게 데이터를 조회할 수 있는 자료구조입니다.", coupang, "DATA_STRUCTURE"),
                    new InterviewQuestion("객체(Object), 인스턴스(Instance), 변수(Variable)의 차이를 설명해 주세요","객체는 클래스 기반 실체, 인스턴스는 생성된 객체, 변수는 데이터를 저장하는 공간입니다.", coupang, "DATA_STRUCTURE"),
                    new InterviewQuestion("알고리즘 복잡도(Time/Space Complexity)에 대해 설명해 주세요","알고리즘 복잡도는 수행 시간과 메모리 사용량을 나타내며, 효율성을 평가합니다.", coupang, "ALGORITHM"),
                    new InterviewQuestion("정렬 방법의 종류와 특징을 설명해 주세요","정렬에는 버블, 선택, 삽입, 퀵, 병합 등이 있으며, 각기 시간복잡도와 공간복잡도가 다릅니다.", coupang, "ALGORITHM"),
                    new InterviewQuestion("최적화 기법에 대해 설명해 주세요","알고리즘과 코드에서 불필요한 연산을 줄여 성능을 개선하는 방법입니다.", coupang, "ALGORITHM"),
                    new InterviewQuestion("병렬성과 동시성의 차이를 설명해 주세요","병렬성은 여러 작업을 동시에 수행하는 것, 동시성은 시간 공유로 여러 작업을 겹쳐 수행하는 것입니다.", coupang, "ALGORITHM"),
                    new InterviewQuestion("트래픽 대응 방법을 설명해 주세요","로드 밸런싱, 캐싱, 큐잉, 스케일 아웃 등을 통해 트래픽 폭주에 대응합니다.", coupang, "NETWORK"),
                    new InterviewQuestion("로드밸런싱(Load Balancing)에 대해 설명해 주세요","여러 서버에 요청을 분산시켜 부하를 줄이고 성능과 안정성을 높이는 방법입니다.", coupang, "NETWORK"),
                    new InterviewQuestion("RDBMS(Relational Database Management System)에 대해 설명해 주세요","관계형 데이터베이스로, 테이블 구조로 데이터를 저장하고 SQL로 조회합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("NoSQL과 RDBMS의 차이를 설명해 주세요","NoSQL은 유연한 스키마를 가진 비관계형 DB이며, RDBMS는 관계형 테이블 구조를 사용합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("DB의 조인(Join) 종류와 특징을 설명해 주세요","내부 조인(INNER), 외부 조인(LEFT, RIGHT), 교차 조인 등이 있으며, 테이블 간 데이터를 결합합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("트랜잭션(Transaction)에서 Propagation과 Isolation을 설명해 주세요","Propagation은 트랜잭션 전파 방식, Isolation은 동시에 실행되는 트랜잭션 간 간섭 정도를 의미합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("PK(Primary Key)가 없는 테이블을 어떻게 처리할 것인지 설명해 주세요","유니크 식별자를 새로 생성하거나 복합 키를 사용해 데이터 무결성을 확보합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("데이터 값이 null일 경우 어떻게 처리할 것인지 설명해 주세요","기본값 설정, 조건부 처리, Null 처리 함수 등을 사용하여 예외 상황을 방지합니다.", coupang, "DATABASE"),
                    new InterviewQuestion("대규모 서비스에서 DB에 직접 조회하지 않고 성능을 높이는 방법을 설명해 주세요","캐시, 큐, 이벤트 기반 처리 등으로 DB 부담을 줄이고 서비스 응답성을 높일 수 있습니다.", coupang, "DATABASE"),
                    new InterviewQuestion("메모리 구조를 설명해 주세요","메모리는 레지스터, 캐시, 주기억장치, 보조기억장치 계층으로 구성되어 있으며 속도와 용량이 다릅니다.", coupang, "COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("static과 non-static의 차이를 설명해 주세요","static은 클래스 단위 공유, non-static은 객체마다 별도 저장됩니다.", coupang, "COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("final 클래스, 메소드, 변수의 사용 차이를 설명해 주세요","final 클래스는 상속 불가, final 메소드는 오버라이드 불가, final 변수는 재할당 불가입니다.", coupang, "COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("OOP(Object-Oriented Programming) 개념을 설명해 주세요","객체와 클래스 개념을 바탕으로 캡슐화, 상속, 다형성을 지원하는 프로그래밍 패러다임입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("TDD(Test-Driven Development)에 대해 설명해 주세요","테스트를 먼저 작성하고 코드를 구현하며, 코드 품질과 안정성을 높이는 개발 방법입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("소프트웨어 아키텍처(Software Architecture)란 무엇인지 설명해 주세요","시스템 구성 요소와 상호작용 구조를 정의하여 유지보수성과 확장성을 높이는 설계 방법입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("MVVM(Model-View-ViewModel) 아키텍처를 설명해 주세요","UI(View)와 로직(ViewModel)을 분리하고, 데이터(Model)와 바인딩해 구조화된 애플리케이션 설계입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("MVC(Model-View-Controller) 모델을 설명해 주세요","데이터를 처리하는 모델, UI를 담당하는 뷰, 로직을 제어하는 컨트롤러로 나누어 구조화한 설계입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("싱글톤 패턴(Singleton Pattern)이 무엇인지 설명해 주세요","클래스의 인스턴스를 하나만 생성하고, 전역에서 접근 가능하도록 하는 디자인 패턴입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("팩토리 패턴(Factory Pattern)이 무엇인지 설명해 주세요","객체 생성 로직을 별도 팩토리 클래스에서 관리하여 코드 결합도를 낮추는 패턴입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("옵저버 패턴(Observer Pattern)이 무엇인지 설명해 주세요","객체 상태 변화를 관찰자에게 알리고, 자동으로 갱신되도록 하는 디자인 패턴입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("디자인 패턴(Design Pattern)이 무엇인지 설명해 주세요","자주 발생하는 설계 문제를 해결하기 위한 재사용 가능한 설계 템플릿입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("프레임워크(Framework)와 정적 라이브러리(Static Library)의 차이를 설명해 주세요","프레임워크는 전체 구조를 제공하고 호출은 사용자가, 정적 라이브러리는 사용자가 호출하면 동작합니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("Spring Singleton과 일반 Singleton 패턴의 차이를 설명해 주세요","Spring Singleton은 스프링 컨테이너 관리로 객체를 공유하고, 일반 Singleton은 코드로 직접 관리합니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("대표적인 소프트웨어 아키텍처 패턴에는 어떤 것이 있는지 설명해 주세요","MVC, MVVM, 레이어드 아키텍처, 마이크로서비스(MSA) 등이 있으며, 구조화와 유지보수성을 높입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("MSA(Microservices Architecture)에 대해 설명해 주세요","서비스를 작은 단위로 나누어 독립 배포 및 확장이 가능하게 하는 아키텍처입니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("자바스크립트(JavaScript)와 자바(Java)의 차이를 설명해 주세요","JavaScript는 인터프리터 언어, 동적 타이핑, 웹 중심이고, Java는 컴파일 언어, 정적 타이핑, 범용 서버/앱 개발에 사용됩니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("스크럼 마스터(Scrum Master)의 역할을 설명해 주세요","팀이 스크럼 프로세스를 따르도록 지원하고, 장애물을 제거하며 효율적 협업을 돕습니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("프레임워크(MVC, MVVM 등)에서 모델 설계가 DB 종류에 따라 달라지는 이유를 설명해 주세요","RDBMS는 관계형 스키마, NoSQL은 유연한 스키마 구조를 요구하므로 설계 방식이 달라집니다.", coupang, "SOFTWARE_DESIGN"),
                    new InterviewQuestion("자바에서 static과 not-static의 차이를 설명해 주세요","static은 클래스 단위 공유, non-static은 객체마다 별도로 존재하며, 접근 방식과 생명주기가 다릅니다.", coupang, "SOFTWARE_DESIGN"),

                    // 카카오
                    new InterviewQuestion("쓰레드는 어떻게 동작하는지 설명해 주세요.","쓰레드는 프로세스 내에서 실행되는 경량 실행 단위로, CPU 스케줄링에 따라 순차적으로 실행됩니다.", kakao,"OS"),
                    new InterviewQuestion("쓰레드풀(Thread Pool)의 개념을 설명해 주세요.","쓰레드풀은 미리 생성된 쓰레드 집합으로 작업을 할당하여 쓰레드 생성/소멸 비용을 줄입니다.", kakao,"OS"),
                    new InterviewQuestion("GC(Garbage Collector, 가비지 컬렉터)는 어떻게 동작하는지 설명해 주세요.","JVM 내 사용되지 않는 객체를 탐지하여 메모리를 회수하며, 여러 알고리즘(마크&스윕 등)을 사용합니다.", kakao,"OS"),
                    new InterviewQuestion("Java에서 Thread Local이란 무엇인지 설명해 주세요.","쓰레드마다 독립적인 변수를 유지하여 동시성 문제를 방지하는 기능입니다.", kakao,"OS"),
                    new InterviewQuestion("Red-Black Tree 알고리즘을 설명해 주세요.","균형 이진 탐색 트리로 삽입/삭제 후 균형을 유지하여 검색, 삽입, 삭제를 O(log n)에 수행합니다.", kakao,"DATA_STRUCTURE"),
                    new InterviewQuestion("Map, Set, List의 차이를 설명해 주세요.","List는 순서가 있고 중복 허용, Set은 순서 없고 중복 불가, Map은 키-값 쌍을 저장합니다.", kakao,"DATA_STRUCTURE"),
                    new InterviewQuestion("HashMap, HashSet의 차이를 설명해 주세요.","HashMap은 키-값 쌍 저장, HashSet은 값만 저장하며 내부적으로 HashMap을 사용합니다.", kakao,"DATA_STRUCTURE"),
                    new InterviewQuestion("해시맵(HashMap)과 해시테이블(HashTable)의 차이를 설명해 주세요.","HashMap은 동기화되지 않아 빠르고 null 키/값 허용, HashTable은 동기화되어 있고 null 허용하지 않습니다.", kakao,"DATA_STRUCTURE"),
                    new InterviewQuestion("삽입정렬(Insertion Sort)을 설명해 주세요.","정렬된 부분과 미정렬 부분으로 나누어 하나씩 적절한 위치에 삽입하며 정렬합니다.", kakao,"ALGORITHM"),
                    new InterviewQuestion("선택정렬(Selection Sort)을 설명해 주세요.","남은 요소 중 최소값을 선택하여 앞쪽으로 이동시키며 정렬합니다.", kakao,"ALGORITHM"),
                    new InterviewQuestion("탐색 알고리즘의 종류를 설명해 주세요.","선형 탐색, 이진 탐색, 해시 탐색 등이 있으며 자료 구조와 성능에 따라 선택합니다.", kakao,"ALGORITHM"),
                    new InterviewQuestion("TCP와 UDP의 차이를 설명해 주세요.","TCP는 연결 지향, 신뢰성 보장, 순서 보장, UDP는 비연결, 속도 우선, 신뢰성 낮음입니다.", kakao,"NETWORK"),
                    new InterviewQuestion("3-way Handshaking 과정을 설명해 주세요.","SYN → SYN-ACK → ACK 순서로 연결을 설정하여 신뢰성 있는 통신을 시작합니다.", kakao,"NETWORK"),
                    new InterviewQuestion("구글 접속 시 에러가 발생하는 이유를 설명해 주세요.","네트워크 문제, DNS 오류, 방화벽, 서버 다운 등 여러 요인이 있을 수 있습니다.", kakao,"NETWORK"),
                    new InterviewQuestion("트랜잭션(Transaction) 개념을 설명해 주세요.","데이터베이스 작업 단위로, ACID 속성을 만족하며 일관성과 신뢰성을 보장합니다.", kakao,"DATABASE"),
                    new InterviewQuestion("N+1 쿼리 문제를 설명해 주세요.","연관 데이터를 조회할 때 반복 쿼리 발생으로 성능 저하가 생기는 문제입니다.", kakao,"DATABASE"),
                    new InterviewQuestion("카산드라DB(Cassandra)와 몽고DB(MongoDB)를 비교해 주세요.","Cassandra는 분산형 Wide Column DB, MongoDB는 문서(Document) 기반 NoSQL DB입니다.", kakao,"DATABASE"),
                    new InterviewQuestion("데이터베이스 정규화(Normalization)를 설명해 주세요.","중복 데이터를 줄이고 무결성을 유지하기 위해 테이블을 구조화하는 과정입니다.", kakao,"DATABASE"),
                    new InterviewQuestion("DAO(Data Access Object)에 대해 설명해 주세요.","DB 접근을 추상화하여 코드와 DB를 분리하고 유지보수를 용이하게 합니다.", kakao,"DATABASE"),
                    new InterviewQuestion("DTO(Data Transfer Object), VO(Value Object), DAO의 차이를 설명해 주세요.","DTO는 데이터 전송용, VO는 값 객체 불변, DAO는 DB 접근 담당 객체입니다.", kakao,"DATABASE"),
                    new InterviewQuestion("Java VM 구조를 설명해 주세요.","클래스 로더, 메모리 영역(Heap, Stack, Method Area), 실행 엔진으로 구성되어 코드를 실행합니다.", kakao,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("메모리 관리 기법을 자세히 설명해 주세요.","힙/스택 관리, GC, 페이징, 스와핑 등을 통해 효율적 메모리 사용을 지원합니다.", kakao,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("순환 참조(Circular Reference)를 설명해 주세요.","객체가 서로 참조하여 GC가 해제하지 못하는 상태를 의미합니다.", kakao,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("WAS(Web Application Server) 메모리 최적화를 설명해 주세요.","힙 사이즈 조절, GC 튜닝, 커넥션 풀과 캐시 활용으로 성능을 개선합니다.", kakao,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("인터페이스와 추상클래스의 차이를 설명해 주세요.","인터페이스는 구현 강제, 다중 상속 가능, 추상클래스는 일부 구현 포함, 단일 상속만 가능합니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MVC1과 MVC2 패턴의 차이를 설명해 주세요.","MVC1은 뷰가 직접 로직 호출, MVC2는 컨트롤러를 통해 로직을 처리하여 구조화가 잘 되어 있습니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Spring Framework의 특징을 설명해 주세요.","의존성 주입(DI), AOP 지원, MVC 구조, 다양한 모듈 제공으로 생산성을 높입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Spring AOP(Aspect-Oriented Programming)를 설명해 주세요.","공통 관심사를 분리하여 로직과 횡단 관심사를 분리하고 코드 재사용성을 높입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MSA(Microservices Architecture)를 설명해 주세요.","서비스를 작게 나누어 독립 배포와 확장이 가능하도록 하는 아키텍처입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향프로그래밍(OOP) 5대 원칙을 설명해 주세요.","SRP, OCP, LSP, ISP, DIP로 설계 결합도를 낮추고 유연성을 높입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("대칭키와 비대칭키 차이를 설명해 주세요.","대칭키는 같은 키로 암/복호화, 비대칭키는 공개/개인 키를 사용하여 보안성을 높입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동기/비동기, 블로킹/논블로킹의 차이를 설명해 주세요.","동기: 순차 처리, 비동기: 비순차 처리, 블로킹: 작업 완료까지 대기, 논블로킹: 즉시 반환합니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("API가 느릴 때 대응 방안을 설명해 주세요.","캐싱, 비동기 처리, 큐 활용, 부하 분산 등으로 성능을 개선할 수 있습니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("AJAX(Asynchronous JavaScript and XML)를 설명해 주세요.","페이지 전체를 새로 고치지 않고 서버와 비동기 통신을 가능하게 하는 기술입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("static에 대해 설명해 주세요.","클래스 단위로 공유되는 변수/메소드로, 객체 생성 없이 접근 가능합니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("HTTP 메소드 종류와 각각의 역할을 설명해 주세요.","GET: 조회, POST: 생성, PUT: 수정, DELETE: 삭제, PATCH: 부분 수정 등입니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("탐색과 정렬 알고리즘 종류를 설명해 주세요.","삽입, 선택, 이진 탐색, BFS, DFS 등 자료 구조에 따라 다양한 알고리즘이 존재합니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("캐시 사용 이유를 설명해 주세요.","데이터 접근 속도를 높이고 DB/서버 부하를 줄여 성능을 향상시키기 위해 사용합니다.", kakao,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("데이터베이스 정규화란 무엇인지 설명해 주세요.","중복 제거와 무결성 유지를 위해 테이블을 구조화하는 과정입니다.", kakao,"SOFTWARE_DESIGN"),

                    // 배민
                    new InterviewQuestion("스레드(Thread)와 프로세스(Process)의 차이를 설명해 주시겠습니까?","프로세스는 독립된 메모리 공간을 가지는 실행 단위이고, 스레드는 프로세스 내에서 메모리를 공유하며 실행되는 단위입니다.", baemin,"OS"),
                    new InterviewQuestion("스레드 프로그래밍 시 주의할 점과 어려움은 무엇입니까?","동기화 문제와 데드락 위험이 있으며 상태 관리가 어려울 수 있으므로 주의해야 합니다.", baemin,"OS"),
                    new InterviewQuestion("연결 리스트(Linked List)의 특징을 설명해 주시겠습니까?","요소가 포인터로 연결되어 있어 삽입과 삭제가 빠르지만, 임의 접근(Random Access)은 느립니다.", baemin,"DATA_STRUCTURE"),
                    new InterviewQuestion("List, Set, Map의 차이를 설명해 주시겠습니까?","List는 순서와 중복을 허용, Set은 중복 불가, Map은 키(Key)-값(Value) 쌍으로 데이터를 저장합니다.", baemin,"DATA_STRUCTURE"),
                    new InterviewQuestion("5개의 슬롯을 가진 해시 테이블(Hash Table)에 1~10을 넣으려면 어떻게 해야 합니까?","해시 함수(Hash Function)와 충돌 해결(Collision Resolution) 방법을 사용해야 합니다.", baemin,"ALGORITHM"),
                    new InterviewQuestion("N+1 문제를 처리하는 방법은 무엇입니까?","즉시 로딩(Fetch Join) 또는 배치 사이즈(Batch Size) 설정으로 해결할 수 있습니다.", baemin,"ALGORITHM"),
                    new InterviewQuestion("트래픽 과부하가 발생할 경우 어떻게 대응하시겠습니까?","로드 밸런싱, 캐싱, 분산 서버, 큐잉 등으로 부하를 분산합니다.", baemin,"NETWORK"),
                    new InterviewQuestion("페이징(Paging)을 사용하는 쿼리를 어떻게 개선할 수 있습니까?","인덱스 최적화, 커버링 인덱스(Covering Index), 키셋 페이징(Keyset Paging)을 활용합니다.", baemin,"DATABASE"),
                    new InterviewQuestion("PostgreSQL과 MySQL의 차이는 무엇입니까?","PostgreSQL은 확장성과 표준 SQL 지원이 강점이고, MySQL은 속도와 사용 편의성이 장점입니다.", baemin,"DATABASE"),
                    new InterviewQuestion("인터프리터 언어(Interpreter)와 객체지향 언어(Object-Oriented Language)의 장단점을 설명해 주시겠습니까?","인터프리터는 실행 속도가 느리지만 이식성이 높고, 객체지향은 재사용성과 확장성이 높지만 설계가 복잡해질 수 있습니다.", baemin,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("MAS(Multi-Agent System)에 대해 설명해 주시겠습니까?","여러 개의 자율적인 에이전트가 협력·경쟁하며 문제를 해결하는 시스템입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향 프로그래밍(OOP)에서 다형성이란 무엇입니까?","동일한 인터페이스로 서로 다른 구현을 실행할 수 있는 성질입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향에서 다형성이 해결하고자 하는 문제는 무엇입니까?","코드 재사용성과 확장성을 높여 유연한 설계를 가능하게 합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("함수형 프로그래밍(Functional Programming)이란 무엇입니까?","순수 함수(Pure Function)와 불변성(Immutability)을 강조하는 선언적 프로그래밍 방식입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("옵저버 패턴(Observer Pattern)의 원리를 설명해 주시겠습니까?","주체 객체의 상태 변화가 옵저버들에게 자동으로 전달되는 구조입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("TDD(Test-Driven Development)란 무엇입니까?","테스트 코드를 먼저 작성하고, 이를 통과하는 코드를 개발하는 방법론입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("스크럼(Scrum)이란 무엇입니까?","애자일 방법론의 한 형태로, 짧은 주기 반복 개발과 팀 협업을 강조합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("디자인 패턴(Design Pattern)이란 무엇이며, 사용하는 이유는 무엇입니까?","검증된 설계 해법으로 코드 재사용성과 유지보수성을 높이기 위해 사용합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MVVM(Model-View-ViewModel)과 MVC(Model-View-Controller) 패턴에서 VM과 C의 역할은 무엇입니까?","Controller는 입력 처리, ViewModel은 데이터와 뷰 바인딩을 담당합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("GoF(Gang of Four) 디자인 패턴은 몇 가지로 분류되며, 각각의 목적은 무엇입니까?","생성(Creational), 구조(Structural), 행위(Behavioral) 패턴으로 나뉘며, 객체 생성, 구조 확장, 행위 캡슐화를 목적으로 합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향 설계 원칙(SOLID)과 디자인 패턴의 관계는 무엇입니까?","SOLID 원칙을 적용하면 유지보수성 높은 설계를 만들 수 있고, 디자인 패턴은 이를 구현하는 검증된 방법입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("웹 접근성(Web Accessibility)이란 무엇입니까?","장애 여부와 상관없이 누구나 웹을 사용할 수 있도록 보장하는 개념입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Delegate와 Lambda 식에 대해서 설명해 주시겠습니까?","메서드를 변수처럼 다루거나 익명 함수를 작성할 수 있는 기능입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("자바스크립트(JavaScript)의 특징은 무엇입니까?","동적 타입, 함수형 프로그래밍 가능, 이벤트 기반 비동기 처리 등을 지원합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("이벤트드리븐(Event-Driven), 이벤트리스너(Event Listener), 이벤트핸들러(Event Handler)의 차이는 무엇입니까?","이벤트드리븐은 동작 구조, 이벤트리스너는 이벤트 감지, 이벤트핸들러는 실제 처리 코드를 의미합니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("테스트 오라클(Test Oracle)이란 무엇입니까?","테스트 결과가 올바른지 판단할 수 있는 기준이나 메커니즘입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("정보보안의 3요소(Confidentiality, Integrity, Availability)는 무엇입니까?","기밀성, 무결성, 가용성을 의미하며, 시스템 보안의 핵심 원칙입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("테스트(Test)와 QA(Quality Assurance)의 차이는 무엇입니까?","테스트는 소프트웨어 오류를 찾는 활동이고, QA는 전체 품질 관리 프로세스입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("JPA(Java Persistence API)와 MyBatis의 차이는 무엇입니까?","JPA는 ORM 기반으로 객체 중심, MyBatis는 SQL 매퍼로 쿼리 중심입니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("JPA를 사용하면서 MyBatis와 비교했을 때 경험상 차이점은 무엇입니까?","JPA는 객체 중심 개발로 편리하지만, 복잡한 쿼리는 MyBatis가 더 직관적일 수 있습니다.", baemin,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("모놀리식(Monolithic) 아키텍처와 마이크로서비스(Microservice) 아키텍처의 차이는 무엇입니까?","모놀리식은 하나의 단일 애플리케이션, 마이크로서비스는 독립 서비스들의 집합으로 구성됩니다.", baemin,"SOFTWARE_DESIGN"),

                    // 당근마켓
                    new InterviewQuestion("멀티 스레드 환경에서 발생할 수 있는 문제와 동기화 처리 방법을 설명해 주세요","경쟁 조건, 데드락 등이 발생할 수 있으며, synchronized, Lock, atomic 연산 등을 사용하여 안전하게 동기화합니다.", danggeun,"OS"),
                    new InterviewQuestion("동시성과 병렬성의 차이를 설명해 주세요","동시성은 여러 작업이 겹쳐서 처리되는 것처럼 보이는 상태이고, 병렬성은 실제로 동시에 실행되는 상태를 의미합니다.", danggeun,"OS"),
                    new InterviewQuestion("스레드와 프로세스의 차이를 설명해 주세요","프로세스는 독립적인 실행 단위이고, 스레드는 프로세스 내에서 자원을 공유하며 실행되는 단위입니다.", danggeun,"OS"),
                    new InterviewQuestion("동기화 방식에는 어떤 것들이 있으며, 어떻게 사용하는지 설명해 주세요","임계 영역 보호, 뮤텍스, 세마포어, 모니터 등을 사용하여 여러 스레드가 안전하게 공유 자원에 접근하도록 합니다.", danggeun,"OS"),
                    new InterviewQuestion("List와 Set의 차이점을 설명해 주세요","List는 순서가 있으며 중복을 허용하고, Set은 순서를 보장하지 않으며 중복을 허용하지 않는 자료구조입니다.", danggeun,"DATA_STRUCTURE"),
                    new InterviewQuestion("다형성이 무엇인지 설명해 주세요","다형성은 동일한 인터페이스를 통해 서로 다른 객체를 다룰 수 있는 객체지향 특성으로, 코드 재사용과 유연성을 높입니다.", danggeun,"DATA_STRUCTURE"),
                    new InterviewQuestion("브라우저는 기본적으로 어떻게 구동되는지 설명해 주세요","브라우저는 HTML, CSS, JS를 파싱하고 렌더 트리를 구성하며, 렌더링 엔진과 JS 엔진을 통해 화면에 출력합니다.", danggeun,"ALGORITHM"),
                    new InterviewQuestion("ACID가 무엇인지 설명해 주세요","트랜잭션의 원자성, 일관성, 고립성, 지속성을 의미하며, 데이터베이스의 일관성을 유지하는 핵심 원칙입니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("데이터베이스 트랜잭션 격리 수준에는 어떤 것들이 있는지 설명해 주세요","Read Uncommitted, Read Committed, Repeatable Read, Serializable 등 트랜잭션 간 상호작용 정도를 정의합니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("트랜잭션 관리는 어떤 방식으로 수행하는지 설명해 주세요","선언적 트랜잭션(@Transactional)이나 프로그래밍 방식으로 관리하며, 커밋과 롤백을 통해 일관성을 유지합니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("DB SELECT 실행 중 락이 걸렸을 때 해결 방법을 설명해 주세요","트랜잭션 격리 수준 조정, 낙관적/비관적 락 사용, 쿼리 튜닝 등으로 락 문제를 해결합니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("SQL Injection이 무엇인지 설명해 주세요","사용자가 입력한 값으로 SQL 쿼리를 조작하여 비정상적인 접근을 시도하는 공격이며, 파라미터 바인딩 등으로 방지합니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("대용량 데이터를 처리하는 방법을 설명해 주세요","배치 처리, 스트리밍 처리, 병렬 처리, 캐싱, 인덱싱 등으로 성능과 안정성을 확보합니다.", danggeun,"DATABASE"),
                    new InterviewQuestion("싱글톤 패턴이 무엇인지 설명해 주세요","애플리케이션 내에서 단 하나의 인스턴스만 생성되어 공유되는 디자인 패턴입니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("GC(Garbage Collection)가 무엇인지 설명해 주세요","사용되지 않는 메모리를 자동으로 회수하여 메모리 누수를 방지하는 메커니즘입니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("DDD(Domain Driven Design)가 무엇인지 설명해 주세요","도메인 중심으로 설계하고, 비즈니스 로직과 모델을 명확히 구분하는 소프트웨어 설계 방법론입니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("대용량 파일 서버에서 데이터를 처리하는 방법을 설명해 주세요","파일 분할, 스트리밍, 캐싱, CDN, 비동기 처리 등을 사용하여 안정성과 성능을 확보합니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("lateinit과 lazy의 차이를 설명해 주세요","lateinit은 변수를 나중에 초기화하고, lazy는 처음 접근 시 초기화하는 지연 초기화 방식입니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동기와 비동기의 차이를 설명해 주세요","동기는 작업이 순차적으로 완료되어야 진행되고, 비동기는 작업을 기다리지 않고 다음 작업을 수행할 수 있습니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("싱글스레드와 멀티스레드의 장단점을 비교해 주세요","싱글스레드는 구현이 간단하지만 병렬 처리 불가, 멀티스레드는 성능 향상 가능하지만 동기화 문제와 복잡성이 존재합니다.", danggeun,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("RDB와 NoSQL의 차이점을 설명해 주세요","RDB는 스키마 기반 관계형 DB이고, NoSQL은 유연한 스키마와 수평 확장성을 지원하며, 구조와 용도가 다릅니다.", danggeun,"DATABASE"),

                    // 토스
                    new InterviewQuestion("병목 현상이 무엇인지 설명해 주시겠어요?","시스템에서 성능을 제한하는 요소를 말하며, CPU, I/O, 메모리 등에서 발생할 수 있습니다.", toss,"OS"),
                    new InterviewQuestion("RDBMS에서 동시성 제어는 어떻게 이루어지는지 설명해 주시겠어요?","트랜잭션 격리 수준과 락을 사용해 여러 트랜잭션이 동시에 수행되어도 데이터 일관성을 유지합니다.", toss,"OS"),
                    new InterviewQuestion("분산 환경에서 동시성 제어는 어떻게 수행되는지 설명해 주시겠어요?","분산 락, 2PC(2단계 커밋) 등으로 여러 노드 간 데이터 일관성을 유지합니다.", toss,"OS"),
                    new InterviewQuestion("배열과 링크드 리스트의 차이점을 설명해 주시겠어요?","배열은 인덱스로 빠른 접근이 가능하지만 크기 변경이 어렵고, 링크드 리스트는 동적 크기 조절과 중간 삽입/삭제가 효율적입니다.", toss,"DATA_STRUCTURE"),
                    new InterviewQuestion("BFS(너비 우선 탐색)와 DFS(깊이 우선 탐색)의 차이점을 설명해 주시겠어요?","BFS는 레벨 순 탐색으로 최단 경로에 유리하며, DFS는 깊이 우선 탐색으로 구현이 간단하지만 스택 오버플로우 주의가 필요합니다.", toss,"DATA_STRUCTURE"),
                    new InterviewQuestion("퀵정렬과 병합정렬의 시간 복잡도와 장단점을 설명해 주시겠어요?","퀵정렬은 평균 O(n log n), 최악 O(n²), 공간 효율적이지만 불안정하며, 병합정렬은 항상 O(n log n), 안정적이지만 추가 메모리가 필요합니다.", toss,"ALGORITHM"),
                    new InterviewQuestion("웹소켓이 무엇인지 설명해 주시겠어요?","클라이언트와 서버 간 양방향 통신을 지원하며, 지속적인 연결과 실시간 데이터 전송에 적합합니다.", toss,"NETWORK"),
                    new InterviewQuestion("대량의 데이터를 처리할 때 고려해야 할 요소들을 설명해 주시겠어요?","처리 속도, 메모리 사용량, 병렬 처리, 인덱스 활용, 파티셔닝 등을 고려합니다.", toss,"DATABASE"),
                    new InterviewQuestion("쿼리 튜닝에서 고려해야 할 사항들을 설명해 주시겠어요?","실행 계획 확인, 인덱스 활용, 불필요한 조인 제거, 정규화/비정규화, 통계 정보 최신화 등을 확인합니다.", toss,"DATABASE"),
                    new InterviewQuestion("인덱스의 종류와 사용 시 주의사항을 설명해 주시겠어요?","B-Tree, Hash, Bitmap 등이 있으며, 과도한 인덱스는 쓰기 성능을 저하시킬 수 있습니다.", toss,"DATABASE"),
                    new InterviewQuestion("조인의 종류와 특징을 설명해 주시겠어요?","INNER JOIN: 공통 데이터, LEFT/RIGHT JOIN: 한쪽 포함, FULL OUTER JOIN: 양쪽 포함", toss,"DATABASE"),
                    new InterviewQuestion("데이터베이스 파티셔닝과 샤딩의 차이를 설명해 주시겠어요?","파티셔닝은 테이블 단위 논리 분할, 샤딩은 DB 서버 단위 물리 분할입니다.", toss,"DATABASE"),
                    new InterviewQuestion("트랜잭션 처리 방법과 ACID 속성을 설명해 주시겠어요?","원자성, 일관성, 격리성, 지속성을 기반으로 트랜잭션을 안전하게 처리합니다.", toss,"DATABASE"),
                    new InterviewQuestion("트랜잭션 격리 수준과 그에 따른 현상을 설명해 주시겠어요?","READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE로 Dirty Read, Non-Repeatable Read, Phantom Read 발생 여부가 다릅니다.", toss,"DATABASE"),
                    new InterviewQuestion("트리거의 정의와 사용 사례를 설명해 주시겠어요?","특정 이벤트 발생 시 자동으로 실행되는 프로시저로, 로그 기록, 데이터 검증 등에 사용합니다.", toss,"DATABASE"),
                    new InterviewQuestion("데이터베이스 성능 향상 방법을 설명해 주시겠어요?","인덱스 사용, 캐싱, 쿼리 최적화, 파티셔닝/샤딩 등을 통해 성능을 개선합니다.", toss,"DATABASE"),
                    new InterviewQuestion("데이터베이스 정규형과 적용 기준을 설명해 주시겠어요?","1NF~3NF로 중복 제거, 무결성 유지, 설계 기준에 따라 적용합니다.", toss,"DATABASE"),
                    new InterviewQuestion("데이터베이스 캐싱 전략과 적용 방법을 설명해 주시겠어요?","읽기 집중 데이터는 메모리 캐시, 분산 캐시를 활용하여 DB 부하를 줄입니다.", toss,"DATABASE"),
                    new InterviewQuestion("스레드와 프로세스의 차이점을 설명해 주시겠어요?","프로세스는 독립 메모리 공간, 스레드는 같은 메모리를 공유하며, 동기화가 필요합니다.", toss,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("스프링 DI(Dependency Injection)를 설명해 주시겠어요?","객체 생성과 의존성 주입을 프레임워크가 담당하여 결합도를 낮춥니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("스프링 AOP 개념과 한계를 설명해 주시겠어요?","횡단 관심사를 모듈화하고, self-invocation 시 AOP 적용이 제한됩니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Kafka 동작 방식을 설명해 주시겠어요?","Producer-Topic-Consumer 구조로 메시지를 비동기 전송하며, 파티션과 오프셋으로 데이터 정렬과 확장성을 지원합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MSA(마이크로서비스 아키텍처)를 설명해 주시겠어요?","작은 단위 서비스로 분리하여 독립 배포, 확장, 장애 격리가 가능합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("DDD(Domain Driven Design)를 설명해 주시겠어요?","도메인 중심 설계로 비즈니스 로직과 모델을 명확히 표현합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("헥사고날 아키텍처를 설명해 주시겠어요?","애플리케이션 핵심 로직과 외부 인터페이스를 분리하여 테스트 용이성과 유연성을 높입니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("CQRS(Command Query Responsibility Segregation)를 설명해 주시겠어요?","읽기와 쓰기 모델을 분리하여 성능과 확장성을 개선하는 패턴입니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("마이크로서비스 간 통신에서 REST와 gRPC 선택 시 고려사항을 설명해 주시겠어요?","REST는 호환성이 높고, gRPC는 성능과 스키마 강제가 가능하며 환경에 맞춰 선택합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("마이크로서비스 환경에서 데이터 일관성 보장 패턴을 설명해 주시겠어요?","Saga, Event Sourcing 등을 사용하여 분산 환경에서 데이터 일관성을 유지합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("서비스 간 장애 격리 패턴을 설명해 주시겠어요?","Circuit Breaker, Bulkhead 등으로 장애가 전파되지 않도록 격리합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("DB 관련 일반적인 설계 고려사항을 설명해 주시겠어요?","정규화, 인덱스, 파티셔닝, 캐싱, 트랜잭션 관리 등을 고려합니다.", toss,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("데이터베이스에서 ACID 원칙이 무엇인지 설명해 주시겠어요?","원자성, 일관성, 격리성, 지속성으로 트랜잭션의 무결성을 보장합니다.", toss,"SOFTWARE_DESIGN"),

                    // 넥슨
                    new InterviewQuestion("스레드와 프로세스의 차이를 설명해 주세요","프로세스는 독립된 메모리 공간을 가진 실행 단위이고, 스레드는 같은 프로세스 내에서 메모리를 공유하는 실행 단위입니다.", nexon,"OS"),
                    new InterviewQuestion("동기와 비동기의 차이를 설명해 주세요","동기는 요청 후 결과를 기다리는 방식이고, 비동기는 요청 후 결과를 기다리지 않고 다음 작업을 수행하는 방식입니다.", nexon,"OS"),
                    new InterviewQuestion("데드락(Deadlock)에 대해 설명해 주세요","두 개 이상의 프로세스가 서로 자원을 점유하며 무한 대기 상태에 빠지는 상황을 말합니다.", nexon,"OS"),
                    new InterviewQuestion("동기화 객체에는 어떤 것들이 있는지 설명해 주세요","뮤텍스(Mutex), 세마포어(Semaphore), 모니터(Monitor) 등이 있으며, 스레드 간 자원 접근을 안전하게 합니다.", nexon,"OS"),
                    new InterviewQuestion("PCB(Process Control Block)에 대해 설명해 주세요","프로세스 정보를 담은 자료 구조로, 프로세스 상태, 프로그램 카운터, 레지스터 정보 등을 포함합니다.", nexon,"OS"),
                    new InterviewQuestion("멀티스레드 환경에서 문제되는 상황과 해결 방법을 설명해 주세요","경쟁 조건, 데드락 발생 가능하며, 뮤텍스, 세마포어 등으로 동기화합니다.", nexon,"OS"),
                    new InterviewQuestion("멀티 스레드와 멀티 프로세스의 장단점을 설명해 주세요","멀티스레드는 메모리 공유로 효율적, 멀티프로세스는 안정성과 독립성이 높습니다.", nexon,"OS"),
                    new InterviewQuestion("트리 자료구조에 대해 설명해 주세요","트리는 계층적 구조를 가진 자료구조로, 부모-자식 관계로 데이터를 표현하며 탐색, 삽입, 삭제가 가능합니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("연결리스트(Linked List)에 대해 설명해 주세요","연결리스트는 노드와 포인터로 구성되어 동적 크기 변경이 가능하며, 삽입과 삭제가 용이합니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("벡터(Vector), 리스트(List), 맵(Map)의 차이를 설명해 주세요","벡터는 동적 배열, 리스트는 연결 리스트, 맵은 키-값 쌍으로 데이터를 저장하는 자료구조입니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("스택 2개로 큐를 구현할 수 있는 방법을 설명해 주세요","한 스택에서 데이터를 넣고, 다른 스택으로 꺼내어 FIFO 구조를 구현합니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("해시맵(HashMap)과 맵(Map)의 차이를 설명해 주세요","해시맵은 해시 함수를 사용하여 키-값을 저장하고, 맵은 일반적으로 정렬된 키-값 구조를 갖습니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("해시맵에서 문자열 키 사용 시 주의점을 설명해 주세요","해시 충돌 가능성을 고려하고, 문자열 해시 함수의 효율성을 평가하여 성능을 최적화해야 합니다.", nexon,"DATA_STRUCTURE"),
                    new InterviewQuestion("퀵소트(Quick Sort)를 설명해 주세요","분할 정복 알고리즘으로 피벗을 기준으로 배열을 분할하고 재귀적으로 정렬하는 알고리즘입니다.", nexon,"ALGORITHM"),
                    new InterviewQuestion("힙 정렬(Heap Sort)을 설명해 주세요","완전 이진 트리 구조를 힙으로 구성하고 최대값 또는 최소값을 반복적으로 추출하여 정렬하는 알고리즘입니다.", nexon,"ALGORITHM"),
                    new InterviewQuestion("1부터 10억까지 랜덤 수 중 중복을 방지하며 뽑는 방법을 설명해 주세요","셔플 알고리즘 또는 해시/비트맵을 사용하여 이미 선택된 수를 추적합니다.", nexon,"ALGORITHM"),
                    new InterviewQuestion("TCP와 UDP의 차이를 설명해 주세요","TCP는 연결 지향으로 신뢰성을 제공하고, UDP는 비연결 지향으로 속도가 빠르지만 신뢰성이 낮습니다.", nexon,"NETWORK"),
                    new InterviewQuestion("HTTP와 HTTPS의 차이를 설명해 주세요","HTTPS는 HTTP에 SSL/TLS 암호화를 적용하여 데이터 전송의 보안성을 확보합니다.", nexon,"NETWORK"),
                    new InterviewQuestion("브라우저가 요청에서 응답까지 처리하는 과정을 설명해 주세요","DNS 조회 → TCP 연결 → HTTP 요청 → 서버 처리 → HTTP 응답 → 렌더링 순으로 동작합니다.", nexon,"NETWORK"),
                    new InterviewQuestion("대용량 트래픽을 처리하는 방법을 설명해 주세요","로드 밸런싱, 캐싱, 분산 처리, 비동기 처리 등을 활용합니다.", nexon,"NETWORK"),
                    new InterviewQuestion("클라우드의 정의를 설명해 주세요","서버, 스토리지, 네트워크 등 컴퓨팅 자원을 인터넷을 통해 제공하는 환경입니다.", nexon,"NETWORK"),
                    new InterviewQuestion("퍼블릭 클라우드와 프라이빗 클라우드의 차이를 설명해 주세요","퍼블릭은 다수 사용자 공유, 프라이빗은 단일 조직 전용 환경입니다.", nexon,"NETWORK"),
                    new InterviewQuestion("서버란 무엇인지 설명해 주세요","클라이언트 요청을 처리하고 데이터를 제공하는 컴퓨터 혹은 프로그램입니다.", nexon,"NETWORK"),
                    new InterviewQuestion("Cookie와 Session의 차이를 설명해 주세요","Cookie는 클라이언트에 저장, Session은 서버에 저장하여 상태를 유지합니다.", nexon,"NETWORK"),
                    new InterviewQuestion("GET과 POST의 차이를 설명해 주세요","GET은 URL에 데이터 노출, POST는 본문에 데이터 포함, 보안과 용량 차이가 있습니다.", nexon,"NETWORK"),
                    new InterviewQuestion("RESTful API를 설명해 주세요","HTTP 메서드를 활용하여 자원(Resource)을 명확히 표현하고 상태를 전송하는 아키텍처 스타일입니다.", nexon,"NETWORK"),
                    new InterviewQuestion("DB 트랜잭션 격리 수준을 설명해 주세요","READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE 등으로 동시성 제어와 일관성을 유지합니다.", nexon,"DATABASE"),
                    new InterviewQuestion("트랜잭션 관리 방식을 설명해 주세요","선언적 트랜잭션과 프로그래밍적 트랜잭션으로 나뉘며, ACID 특성을 유지하면서 데이터 일관성을 보장합니다.", nexon,"DATABASE"),
                    new InterviewQuestion("RDB와 NoSQL의 차이를 설명해 주세요","RDB는 스키마 기반 관계형, NoSQL은 비정형 데이터를 유연하게 처리하며 확장성이 뛰어납니다.", nexon,"DATABASE"),
                    new InterviewQuestion("SQL Injection 취약점과 방어 방법을 설명해 주세요","악의적 SQL 삽입 공격으로 데이터가 유출될 수 있으며, PreparedStatement와 입력 검증으로 방어합니다.", nexon,"DATABASE"),
                    new InterviewQuestion("인덱싱(Indexing)이 무엇인지 설명해 주세요","검색 속도를 높이기 위해 데이터 구조를 만들어 참조를 효율적으로 하는 방법입니다.", nexon,"DATABASE"),
                    new InterviewQuestion("정규화(Normalization)와 반정규화(Denormalization)를 설명해 주세요","정규화는 중복 최소화, 반정규화는 성능 최적화를 위해 일부 중복 허용입니다.", nexon,"DATABASE"),
                    new InterviewQuestion("인덱스와 조인을 설명해 주세요","인덱스는 검색 속도 향상, 조인은 테이블 간 데이터를 결합하는 방법입니다.", nexon,"DATABASE"),
                    new InterviewQuestion("OLAP와 OLTP의 차이를 설명해 주세요","OLAP는 분석용, OLTP는 트랜잭션 처리용 시스템입니다.", nexon,"DATABASE"),
                    new InterviewQuestion("GC(Garbage Collection)의 동작 원리를 설명해 주세요","사용하지 않는 객체를 자동으로 메모리에서 해제하여 메모리 누수를 방지합니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("힙 영역(Heap)에 대해 설명해 주세요","동적 메모리가 할당되는 영역으로, 객체나 배열을 런타임에 생성합니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("PCB(Process Control Block)에 대해 설명해 주세요","프로세스 정보를 담은 자료 구조로, 프로세스 상태, 프로그램 카운터, 레지스터 정보 등을 포함합니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("RTTI(Runtime Type Information)에 대해 설명해 주세요","실행 시 객체 타입 정보를 제공하여 안전한 타입 캐스팅과 동적 타입 확인을 가능하게 합니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("C언어 함수 호출 규약 3가지를 설명해 주세요","cdecl, stdcall, fastcall 등으로 함수 호출 시 스택과 레지스터 사용 규칙이 다릅니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("스태틱 캐스트와 다이나믹 캐스트를 설명해 주세요","스태틱 캐스트는 컴파일 시 변환, 다이나믹 캐스트는 런타임 타입 체크를 수행합니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("싱글톤 패턴(Singleton Pattern)에 대해 설명해 주세요","애플리케이션 전체에서 객체를 하나만 생성하도록 보장하는 설계 패턴입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("DDD(Domain-Driven Design)에 대해 설명해 주세요","복잡한 비즈니스 로직을 도메인 모델 중심으로 설계하여 유지보수성을 높이는 접근 방식입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("MVC 패턴을 설명해 주세요","Model, View, Controller로 역할을 분리하여 개발과 유지보수를 효율적으로 하는 디자인 패턴입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("다형성(Polymorphism)에 대해 설명해 주세요","하나의 인터페이스로 여러 형태의 객체를 다룰 수 있어 코드 재사용성과 유연성을 높입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동시성과 병렬성의 차이를 설명해 주세요","동시성은 여러 작업을 동시에 진행하는 듯 처리, 병렬성은 실제로 여러 작업이 동시에 실행되는 것을 말합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동기화(Synchronization)의 원리와 방식에 대해 설명해 주세요","공유 자원 접근 시 충돌을 방지하며, 뮤텍스, 세마포어, 모니터 등으로 구현됩니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("GC의 세대별 구분 이유를 설명해 주세요","객체의 수명에 따라 메모리를 구분하여 효율적인 수집과 성능 최적화를 위해 세대를 나눕니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동적 라이브러리(DLL)와 정적 라이브러리(STATIC)의 차이를 설명해 주세요","동적 라이브러리는 런타임에 로드되고, 정적 라이브러리는 컴파일 시 결합되어 실행 파일에 포함됩니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("생성자 내부에서 가상함수를 호출하면 어떻게 되는지 설명해 주세요","생성자에서는 파생 클래스의 가상함수가 호출되지 않고, 현재 클래스 버전이 실행됩니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("순수가상함수와 일반 가상함수의 차이를 설명해 주세요","순수가상함수는 반드시 파생 클래스에서 구현해야 하며, 일반 가상함수는 선택적으로 오버라이드 가능합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("C와 C++의 가장 큰 차이를 설명해 주세요","C는 절차지향, C++은 객체지향 기능을 추가한 언어입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("C++과 C#의 가장 큰 차이를 설명해 주세요","C++은 컴파일 시점 메모리 관리, C#은 .NET 환경에서 가비지 컬렉션을 제공합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("C언어 함수 호출 규약 3가지를 설명해 주세요","cdecl, stdcall, fastcall 등으로 스택과 레지스터 사용 방식이 다릅니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("컴파일러 최적화를 막는 방법을 설명해 주세요","volatile 키워드, 메모리 장벽 등을 사용하여 특정 변수 최적화를 방지할 수 있습니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("멀티스레딩/멀티프로세스에서 스케줄링 기법을 설명해 주세요","선점형, 비선점형, 라운드로빈, 우선순위 기반 등으로 CPU 시간을 분배합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("오버로딩과 오버라이딩의 차이를 설명해 주세요","오버로딩은 같은 이름 다른 매개변수, 오버라이딩은 상속 시 메서드 재정의입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("메모리 단편화란 무엇인지 설명해 주세요","메모리가 작은 조각으로 나뉘어 연속 공간 확보가 어려워지는 현상입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("PHP에 Thread Pool이 있는지 설명해 주세요","기본적으로 PHP는 Thread Pool을 제공하지 않으며, 확장 모듈이나 별도 서버에서 구현해야 합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("Java 제네릭과 C++ 템플릿의 차이를 설명해 주세요","Java 제네릭은 런타임 타입 정보가 삭제되고 타입 안전성을 제공, C++ 템플릿은 컴파일 시 코드 생성과 타입 구체화를 수행합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("객체지향 5원칙(객체지향 설계 원칙)을 설명해 주세요","SOLID: 단일 책임, 개방-폐쇄, 리스코프 치환, 인터페이스 분리, 의존성 역전 원칙입니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("순수가상함수와 일반 가상함수의 차이를 설명해 주세요","순수가상함수는 반드시 구현해야 하고, 일반 가상함수는 선택적으로 재정의 가능합니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("생성자에서 가상함수를 호출하면 어떻게 되는지 설명해 주세요","생성자에서는 파생 클래스 버전이 아니라 현재 클래스 버전이 호출됩니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("동적 라이브러리와 정적 라이브러리의 차이를 설명해 주세요","동적은 런타임 로드, 정적은 컴파일 시 결합됩니다.", nexon,"SOFTWARE_DESIGN"),
                    new InterviewQuestion("메모리 단편화란 무엇인지 설명해 주세요","메모리가 작은 조각으로 나뉘어 연속 공간 확보가 어려워지는 현상입니다.", nexon,"COMPUTER_ARCHITECTURE"),
                    new InterviewQuestion("트랜잭션 4가지 격리수준을 설명해 주세요","READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE입니다.", nexon,"DATABASE"),
                    new InterviewQuestion("트랜잭션이 많아지면 성능이 느려지는 이유를 설명해 주세요","잠금 증가와 컨텍스트 스위칭, 디스크 I/O 증가로 인해 병목이 발생합니다.", nexon,"DATABASE")

                    );

            // 중복 체크
            for (InterviewQuestion q : questions) {
                if (!questionRepository.existsByQuestion(q.getQuestion())) questionRepository.save(q);
            }
        };
    }
}
